name: "generate-changelog"
on:
  push:
    tags-ignore:
      - '*RC*'

jobs:
  
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: viniciusCSreis/action-changelog-generator@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-name: your_repo_name
        repo-user: your_repo_user
